name: flutter_map_onboarding
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  auto_route: ^7.8.4
  introduction_screen: ^3.1.12
  lottie: ^3.0.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  flutter_vlc_player: ^7.4.2
  cupertino_icons: ^1.0.6
  easy_localization: ^3.0.3
  firebase_core: ^2.32.0
  firebase_analytics: ^10.10.7
  cloud_firestore: ^4.17.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  auto_route_generator: ^7.3.0

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/explore.json
    - assets/location.json
    - assets/man.json
    - assets/lang/
