// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvPboc2XkgRzkdpiPJMACWWuowdebLlz0',
    appId: '1:768676626786:web:75c9e99a33a2b0ec95ec3b',
    messagingSenderId: '768676626786',
    projectId: 'flutter-map-onboarding',
    authDomain: 'flutter-map-onboarding.firebaseapp.com',
    storageBucket: 'flutter-map-onboarding.firebasestorage.app',
    measurementId: 'G-NDD69MGPRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYWKmJff9w9FETmKs52DnKvSov4mKDqls',
    appId: '1:768676626786:android:c3a6cb70b86b8a6d95ec3b',
    messagingSenderId: '768676626786',
    projectId: 'flutter-map-onboarding',
    storageBucket: 'flutter-map-onboarding.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlnUFSvB8BOShISsjrnY0buFJPNjbWKwI',
    appId: '1:768676626786:ios:9b5cf5ecdea61cd695ec3b',
    messagingSenderId: '768676626786',
    projectId: 'flutter-map-onboarding',
    storageBucket: 'flutter-map-onboarding.firebasestorage.app',
    iosBundleId: 'com.example.flutterMapOnboarding',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlnUFSvB8BOShISsjrnY0buFJPNjbWKwI',
    appId: '1:768676626786:ios:9b5cf5ecdea61cd695ec3b',
    messagingSenderId: '768676626786',
    projectId: 'flutter-map-onboarding',
    storageBucket: 'flutter-map-onboarding.firebasestorage.app',
    iosBundleId: 'com.example.flutterMapOnboarding',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvPboc2XkgRzkdpiPJMACWWuowdebLlz0',
    appId: '1:768676626786:web:945f79b33e3e0b8d95ec3b',
    messagingSenderId: '768676626786',
    projectId: 'flutter-map-onboarding',
    authDomain: 'flutter-map-onboarding.firebaseapp.com',
    storageBucket: 'flutter-map-onboarding.firebasestorage.app',
    measurementId: 'G-R7VCNRRQVT',
  );
}
